# Week 4 — Exploratory Data Analysis

## Objective
Perform descriptive statistics, distribution analysis, correlation analysis and initial EDA relevant to IPL player valuation.

In [1]:
auction.describe()

       PRICE(In crore Indian Rupees)        YEAR
count                       56.000000    56.0000
mean                         7.636607  2017.0000
std                          3.295155     2.0181
min                          3.000000  2014.0000
25%                          5.000000  2015.0000
50%                          7.000000  2017.0000
75%                          9.525000  2019.0000
max                         16.000000  2020.0000

       PRICE(In crore Indian Rupees)        YEAR
count                       56.000000    56.0000
mean                         7.636607  2017.0000
std                          3.295155     2.0181
min                          3.000000  2014.0000
25%                          5.000000  2015.0000
50%                          7.000000  2017.0000
75%                          9.525000  2019.0000
max                         16.000000  2020.0000

In [1]:
batsmen.describe()

              POS         Mat        Inns  ...          50          4s          6s
count  100.000000  100.000000  100.000000  ...  100.000000  100.000000  100.000000
mean    50.500000   85.130000   76.630000  ...   10.360000  170.280000   68.380000
std     29.011492   46.042066   41.753402  ...    9.594316  121.580341   55.246332
min      1.000000   16.000000   16.000000  ...    0.000000   34.000000    9.000000
25%     25.750000   49.000000   45.000000  ...    4.000000   82.000000   34.000000
50%     50.500000   76.000000   67.500000  ...    8.000000  127.000000   46.500000
75%     75.250000  110.750000   95.250000  ...   13.000000  240.000000   82.500000
max    100.000000  193.000000  189.000000  ...   44.000000  524.000000  326.000000

[8 rows x 12 columns]

              POS         Mat        Inns  ...          50          4s          6s
count  100.000000  100.000000  100.000000  ...  100.000000  100.000000  100.000000
mean    50.500000   85.130000   76.630000  ...   10.360000  170.280000   68.380000
std     29.011492   46.042066   41.753402  ...    9.594316  121.580341   55.246332
min      1.000000   16.000000   16.000000  ...    0.000000   34.000000    9.000000
25%     25.750000   49.000000   45.000000  ...    4.000000   82.000000   34.000000
50%     50.500000   76.000000   67.500000  ...    8.000000  127.000000   46.500000
75%     75.250000  110.750000   95.250000  ...   13.000000  240.000000   82.500000
max    100.000000  193.000000  189.000000  ...   44.000000  524.000000  326.000000

[8 rows x 12 columns]

In [1]:
bowlers.describe()

              POS         Mat        Inns  ...          SR          4w          5w
count  100.000000  100.000000  100.000000  ...  100.000000  100.000000  100.000000
mean    50.500000   68.350000   62.970000  ...   21.684600    0.900000    0.150000
std     29.011492   40.027106   33.354677  ...    4.241365    1.141504    0.411329
min      1.000000   18.000000   18.000000  ...   13.220000    0.000000    0.000000
25%     25.750000   37.750000   37.750000  ...   19.367500    0.000000    0.000000
50%     50.500000   56.500000   55.000000  ...   21.005000    1.000000    0.000000
75%     75.250000   90.250000   82.250000  ...   23.115000    1.000000    0.000000
max    100.000000  193.000000  157.000000  ...   37.060000    6.000000    2.000000

[8 rows x 12 columns]

              POS         Mat        Inns  ...          SR          4w          5w
count  100.000000  100.000000  100.000000  ...  100.000000  100.000000  100.000000
mean    50.500000   68.350000   62.970000  ...   21.684600    0.900000    0.150000
std     29.011492   40.027106   33.354677  ...    4.241365    1.141504    0.411329
min      1.000000   18.000000   18.000000  ...   13.220000    0.000000    0.000000
25%     25.750000   37.750000   37.750000  ...   19.367500    0.000000    0.000000
50%     50.500000   56.500000   55.000000  ...   21.005000    1.000000    0.000000
75%     75.250000   90.250000   82.250000  ...   23.115000    1.000000    0.000000
max    100.000000  193.000000  157.000000  ...   37.060000    6.000000    2.000000

[8 rows x 12 columns]

In [1]:
auction.groupby('YEAR')[price_col].agg(['count','mean','min','max']).round(2)

      count   mean  min   max
YEAR
2014      8   8.00  5.0  14.0
2015      8   6.44  3.0  16.0
2016      8   6.66  4.5   9.5
2017      8   6.59  3.5  14.5
2018      8  10.38  9.0  12.5
2019      8   6.30  5.0   8.4
2020      8   9.09  5.5  15.5

      count   mean  min   max
YEAR
2014      8   8.00  5.0  14.0
2015      8   6.44  3.0  16.0
2016      8   6.66  4.5   9.5
2017      8   6.59  3.5  14.5
2018      8  10.38  9.0  12.5
2019      8   6.30  5.0   8.4
2020      8   9.09  5.5  15.5

In [1]:
auction.groupby('TYPE')[price_col].agg(['count','mean','min','max']).round(2)

               count   mean   min   max
TYPE
All-Rounder       23   8.21   4.2  15.5
Batsman           11   7.95   3.0  16.0
Bowler            20   6.42   3.5  12.0
Wicket Keeper      2  11.50  10.5  12.5

               count   mean   min   max
TYPE
All-Rounder       23   8.21   4.2  15.5
Batsman           11   7.95   3.0  16.0
Bowler            20   6.42   3.5  12.0
Wicket Keeper      2  11.50  10.5  12.5

In [1]:
batsmen.nlargest(10,'Runs')[['PLAYER','Runs','Avg','SR']]

           PLAYER  Runs    Avg      SR
0      ViratKohli  5412  37.84  131.61
1    Suresh Raina  5368  33.34  137.14
2    Rohit Sharma  4898  31.60  130.82
3    David Warner  4706  43.17  142.39
4  Shikhar Dhawan  4579  33.42  124.80
5     Chris Gayle  4484  41.13  151.02
6        MS Dhoni  4432  42.20  137.85
7   Robin Uthappa  4411  28.83  130.50
8  AB de Villiers  4395  39.95  151.23
9  Gautam Gambhir  4217  31.23  123.88

           PLAYER  Runs    Avg      SR
0      ViratKohli  5412  37.84  131.61
1    Suresh Raina  5368  33.34  137.14
2    Rohit Sharma  4898  31.60  130.82
3    David Warner  4706  43.17  142.39
4  Shikhar Dhawan  4579  33.42  124.80
5     Chris Gayle  4484  41.13  151.02
6        MS Dhoni  4432  42.20  137.85
7   Robin Uthappa  4411  28.83  130.50
8  AB de Villiers  4395  39.95  151.23
9  Gautam Gambhir  4217  31.23  123.88

In [1]:
bowlers.nlargest(10,'Wkts')[['PLAYER','Wkts','Avg','Econ','SR']]

                PLAYER  Wkts    Avg  Econ     SR
0        LasithMalinga   170  19.80  7.14  16.62
1          Amit Mishra   157  24.19  7.35  19.75
2      Harbhajan Singh   150  26.44  7.05  22.49
3        Piyush Chawla   150  27.14  7.82  20.82
4         Dwayne Bravo   147  24.60  8.39  17.59
5    Bhuvneshwar Kumar   133  23.71  7.24  19.63
6  Ravichandran Ashwin   125  26.48  6.79  23.39
7         Sunil Narine   122  23.31  6.67  20.96
8          Umesh Yadav   119  29.37  8.45  20.84
9      Ravindra Jadeja   108  29.18  7.57  23.10

                PLAYER  Wkts    Avg  Econ     SR
0        LasithMalinga   170  19.80  7.14  16.62
1          Amit Mishra   157  24.19  7.35  19.75
2      Harbhajan Singh   150  26.44  7.05  22.49
3        Piyush Chawla   150  27.14  7.82  20.82
4         Dwayne Bravo   147  24.60  8.39  17.59
5    Bhuvneshwar Kumar   133  23.71  7.24  19.63
6  Ravichandran Ashwin   125  26.48  6.79  23.39
7         Sunil Narine   122  23.31  6.67  20.96
8          Umesh Yadav   119  29.37  8.45  20.84
9      Ravindra Jadeja   108  29.18  7.57  23.10

In [1]:
batsmen.select_dtypes(include=np.number).corr().round(2)

       POS   Mat  Inns    NO  Runs   Avg    BF    SR   100    50    4s    6s
POS   1.00 -0.74 -0.85 -0.38 -0.91 -0.47 -0.91 -0.10 -0.47 -0.82 -0.88 -0.74
Mat  -0.74  1.00  0.96  0.76  0.80  0.02  0.80  0.04  0.28  0.62  0.73  0.66
Inns -0.85  0.96  1.00  0.65  0.92  0.16  0.92  0.04  0.37  0.76  0.86  0.75
NO   -0.38  0.76  0.65  1.00  0.43  0.04  0.42  0.05  0.04  0.24  0.27  0.43
Runs -0.91  0.80  0.92  0.43  1.00  0.46  0.99  0.12  0.56  0.94  0.96  0.83
Avg  -0.47  0.02  0.16  0.04  0.46  1.00  0.43  0.26  0.48  0.57  0.41  0.44
BF   -0.91  0.80  0.92  0.42  0.99  0.43  1.00  0.00  0.51  0.92  0.97  0.76
SR   -0.10  0.04  0.04  0.05  0.12  0.26  0.00  1.00  0.26  0.13  0.06  0.42
100  -0.47  0.28  0.37  0.04  0.56  0.48  0.51  0.26  1.00  0.55  0.52  0.65
50   -0.82  0.62  0.76  0.24  0.94  0.57  0.92  0.13  0.55  1.00  0.93  0.74
4s   -0.88  0.73  0.86  0.27  0.96  0.41  0.97  0.06  0.52  0.93  1.00  0.69
6s   -0.74  0.66  0.75  0.43  0.83  0.44  0.76  0.42  0.65  0.74  0.69  1.00

       POS   Mat  Inns    NO  Runs   Avg    BF    SR   100    50    4s    6s
POS   1.00 -0.74 -0.85 -0.38 -0.91 -0.47 -0.91 -0.10 -0.47 -0.82 -0.88 -0.74
Mat  -0.74  1.00  0.96  0.76  0.80  0.02  0.80  0.04  0.28  0.62  0.73  0.66
Inns -0.85  0.96  1.00  0.65  0.92  0.16  0.92  0.04  0.37  0.76  0.86  0.75
NO   -0.38  0.76  0.65  1.00  0.43  0.04  0.42  0.05  0.04  0.24  0.27  0.43
Runs -0.91  0.80  0.92  0.43  1.00  0.46  0.99  0.12  0.56  0.94  0.96  0.83
Avg  -0.47  0.02  0.16  0.04  0.46  1.00  0.43  0.26  0.48  0.57  0.41  0.44
BF   -0.91  0.80  0.92  0.42  0.99  0.43  1.00  0.00  0.51  0.92  0.97  0.76
SR   -0.10  0.04  0.04  0.05  0.12  0.26  0.00  1.00  0.26  0.13  0.06  0.42
100  -0.47  0.28  0.37  0.04  0.56  0.48  0.51  0.26  1.00  0.55  0.52  0.65
50   -0.82  0.62  0.76  0.24  0.94  0.57  0.92  0.13  0.55  1.00  0.93  0.74
4s   -0.88  0.73  0.86  0.27  0.96  0.41  0.97  0.06  0.52  0.93  1.00  0.69
6s   -0.74  0.66  0.75  0.43  0.83  0.44  0.76  0.42  0.65  0.74  0.69  1.00

In [1]:
bowlers.select_dtypes(include=np.number).corr().round(2)

       POS   Mat  Inns    Ov  Runs  Wkts  BBI   Avg  Econ    SR    4w    5w
POS   1.00 -0.66 -0.86 -0.89 -0.90 -0.92  NaN  0.29  0.16  0.24 -0.47 -0.32
Mat  -0.66  1.00  0.89  0.79  0.79  0.71  NaN  0.15 -0.16  0.23  0.32  0.22
Inns -0.86  0.89  1.00  0.97  0.97  0.92  NaN  0.01 -0.19  0.09  0.40  0.30
Ov   -0.89  0.79  0.97  1.00  0.99  0.96  NaN -0.07 -0.25  0.03  0.43  0.33
Runs -0.90  0.79  0.97  0.99  1.00  0.95  NaN -0.03 -0.11  0.01  0.40  0.32
Wkts -0.92  0.71  0.92  0.96  0.95  1.00  NaN -0.28 -0.20 -0.21  0.56  0.36
BBI    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
Avg   0.29  0.15  0.01 -0.07 -0.03 -0.28  NaN  1.00  0.29  0.91 -0.45 -0.14
Econ  0.16 -0.16 -0.19 -0.25 -0.11 -0.20  NaN  0.29  1.00 -0.13 -0.16 -0.06
SR    0.24  0.23  0.09  0.03  0.01 -0.21  NaN  0.91 -0.13  1.00 -0.40 -0.12
4w   -0.47  0.32  0.40  0.43  0.40  0.56  NaN -0.45 -0.16 -0.40  1.00  0.38
5w   -0.32  0.22  0.30  0.33  0.32  0.36  NaN -0.14 -0.06 -0.12  0.38  1.00

       POS   Mat  Inns    Ov  Runs  Wkts  BBI   Avg  Econ    SR    4w    5w
POS   1.00 -0.66 -0.86 -0.89 -0.90 -0.92  NaN  0.29  0.16  0.24 -0.47 -0.32
Mat  -0.66  1.00  0.89  0.79  0.79  0.71  NaN  0.15 -0.16  0.23  0.32  0.22
Inns -0.86  0.89  1.00  0.97  0.97  0.92  NaN  0.01 -0.19  0.09  0.40  0.30
Ov   -0.89  0.79  0.97  1.00  0.99  0.96  NaN -0.07 -0.25  0.03  0.43  0.33
Runs -0.90  0.79  0.97  0.99  1.00  0.95  NaN -0.03 -0.11  0.01  0.40  0.32
Wkts -0.92  0.71  0.92  0.96  0.95  1.00  NaN -0.28 -0.20 -0.21  0.56  0.36
BBI    NaN   NaN   NaN   NaN   NaN   NaN  NaN   NaN   NaN   NaN   NaN   NaN
Avg   0.29  0.15  0.01 -0.07 -0.03 -0.28  NaN  1.00  0.29  0.91 -0.45 -0.14
Econ  0.16 -0.16 -0.19 -0.25 -0.11 -0.20  NaN  0.29  1.00 -0.13 -0.16 -0.06
SR    0.24  0.23  0.09  0.03  0.01 -0.21  NaN  0.91 -0.13  1.00 -0.40 -0.12
4w   -0.47  0.32  0.40  0.43  0.40  0.56  NaN -0.45 -0.16 -0.40  1.00  0.38
5w   -0.32  0.22  0.30  0.33  0.32  0.36  NaN -0.14 -0.06 -0.12  0.38  1.00

## Initial EDA Insights

- The auction dataset contains **56 records from 2014–2020**.
- The highest auction price in the supplied dataset is **₹16 crore**.
- **Virat Kohli** is the highest run scorer in the supplied Top-100 batsmen dataset.
- **Lasith Malinga** is the highest wicket taker in the supplied Top-100 bowlers dataset.
- The matches dataset contains **756 matches from 2008–2019**.
- Auction price and player-performance distributions should be examined for skewness and extreme values before modelling.
- Correlation analysis helps identify related variables and possible redundancy before feature engineering.